version: '3.9'
services:
  client:
    build: ./client/
    ports:
      - "4000:4000"
    volumes:
      - ./client:/client
  server:
    build: ./server/
    ports:
      - "3000:3000"
    volumes:
      - ./server:/server